
-- CREATE TABLE BY ISSUE
-- 
-- CREATE ISSUE_KEY (PER MERCHANT, CREATE ISSUE BY CONSOLIDATING REASON||DETAILED_REASON TO DEFINE)


CREATE OR REPLACE TABLE `cases-478017.sumup.tbl_issue_merchant` AS 

WITH base1 AS (
  SELECT
    TOUCHPOINT_ID,
    STATUS,
    MERCHANT_ID,
    CONCAT(MERCHANT_ID, '--', REASON,' -- ',DETAILED_REASON) AS ISSUE_KEY,
    CHANNEL,
    MCC_GROUP,
    COUNTRY,
    AGENT_COMPANY,
    AGENT_ID,
    SAFE_DIVIDE(TOTAL_HANDLING_TIME_SECONDS,3600) AS TOTAL_HANDLING_TIME_HR,
    SAFE_DIVIDE(RESPONSE_TIME_SECONDS,3600) AS RESPONSE_TIME_HR,
    SAFE_DIVIDE(QUEUE_WAITING_TIME_SECONDS,3600) AS QUEUE_WAITING_TIME_HR,    
    TIMESTAMP(CREATED_AT) AS CREATED_TIME,
    MIN(TIMESTAMP(CREATED_AT)) OVER (
      PARTITION BY CONCAT(MERCHANT_ID, '--', REASON,' -- ',DETAILED_REASON)
      ORDER BY TIMESTAMP(CREATED_AT)
    ) AS FIRST_TOUCHPOINT,
    MAX(TIMESTAMP(CREATED_AT)) OVER (
      PARTITION BY CONCAT(MERCHANT_ID, '--', REASON,' -- ',DETAILED_REASON)
      ORDER BY TIMESTAMP(CREATED_AT) DESC
    ) AS LAST_TOUCHPOINT
  FROM `cases-478017.sumup.rawdata`
--  TEST/VALIDATION: WHERE MERCHANT_ID IN (-9222559069329372688,-9220325424708406916,-9221326501342579175) 
)

  SELECT    
    COUNTRY,
    MCC_GROUP,
    MERCHANT_ID,
    ISSUE_KEY,
    COUNT(DISTINCT TOUCHPOINT_ID) AS COUNT_TOUCHPOINTS,
    COUNT(DISTINCT AGENT_ID) AS COUNT_AGENTS,
    COUNT(DISTINCT AGENT_COMPANY) AS COUNT_AGENT_COMPANY,
    MAX(CASE WHEN CREATED_TIME = FIRST_TOUCHPOINT then TOUCHPOINT_ID else NULL end) as TOUCHPOINT_ID_FIRST,
    MAX(CASE WHEN CREATED_TIME = LAST_TOUCHPOINT then TOUCHPOINT_ID else NULL end) as TOUCHPOINT_ID_LAST,
    MAX(CASE WHEN CREATED_TIME = FIRST_TOUCHPOINT then CHANNEL end) as CHANNEL_FIRST,
    MAX(CASE WHEN CREATED_TIME = LAST_TOUCHPOINT then CHANNEL end) as CHANNEL_LAST,
    MAX(CASE WHEN CREATED_TIME = FIRST_TOUCHPOINT then AGENT_COMPANY end) as AGENT_COMPANY_FIRST,
    MAX(CASE WHEN CREATED_TIME = LAST_TOUCHPOINT then AGENT_COMPANY end) as AGENT_COMPANY_LAST,
    MAX(CASE WHEN STATUS = 'Resolved' THEN 1 ELSE 0 END) AS ISSUE_RESOLVED,
    MAX(CASE WHEN STATUS = 'Resolved' then TIMESTAMP_DIFF(base1.LAST_TOUCHPOINT, base1.FIRST_TOUCHPOINT, DAY) END) AS DAYS_RESOLVED,
    MAX(CASE WHEN STATUS = 'Resolved' AND TIMESTAMP_DIFF(base1.LAST_TOUCHPOINT, base1.FIRST_TOUCHPOINT, DAY) <= 7 then 1 ELSE 0 END) AS ISSUE_RESOLVED_7D,
    MAX(CASE WHEN STATUS <> 'Resolved' then TIMESTAMP_DIFF(base1.LAST_TOUCHPOINT, base1.FIRST_TOUCHPOINT, DAY) END) AS DAYS_NOT_RESOLVED,
    SUM(TOTAL_HANDLING_TIME_HR) AS TOTAL_HANDLING_TIME_HR,
    SUM(RESPONSE_TIME_HR) AS RESPONSE_TIME_HR,
    SUM(QUEUE_WAITING_TIME_HR) as QUEUE_WAITING_TIME_HR
  FROM base1
    GROUP BY      
      COUNTRY,
      MCC_GROUP,
      MERCHANT_ID,
      ISSUE_KEY
      ;

-- Validation OK - values are in line 
-- SELECT
--   count(distinct ISSUE_KEY) as total_issues,
--   SUM(count_touchpoints) as total_touchpoints
-- FROM `cases-478017.sumup.tbl_issue_merchant`

-- Row	total_issues	total_touchpoints
-- 1	291384	350785	
