--------------------------------------------
-- TASKS:
------------------

--------------------
-- 1) RESOLUTION DAYS WINDOW
--------------------

-- tested some timeframe windows and possible difference between channel and country
-- % percent of issues resolved per CHANNEL_LAST (I consider the last channel as channel that resolved)

with temp as (
SELECT 
--  COUNTRY,
--  COALESCE(CHANNEL_LAST,CHANNEL_FIRST) AS CHANNEL,
  COUNT(DISTINCT ISSUE_KEY) AS COUNT_ISSUE,
  ROUND(SAFE_DIVIDE(SUM(ISSUE_RESOLVED),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED,
  ROUND(SAFE_DIVIDE(SUM(ISSUE_RESOLVED_7D),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_7D, -- current timeframe
  ROUND(SAFE_DIVIDE(SUM(CASE WHEN DAYS_RESOLVED = 0 THEN 1 ELSE 0 END),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_0D,
  ROUND(SAFE_DIVIDE(SUM(CASE WHEN DAYS_RESOLVED <= 1 THEN 1 ELSE 0 END),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_1D,
  ROUND(SAFE_DIVIDE(SUM(CASE WHEN DAYS_RESOLVED <= 3 THEN 1 ELSE 0 END),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_3D,
  ROUND(SAFE_DIVIDE(SUM(CASE WHEN DAYS_RESOLVED <= 5 THEN 1 ELSE 0 END),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_5D,
  ROUND(SAFE_DIVIDE(SUM(CASE WHEN DAYS_RESOLVED <= 10 THEN 1 ELSE 0 END),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_10D
FROM `cases-478017.sumup.tbl_issue_merchant` 
--GROUP BY 1 
)
SELECT 
--  COUNTRY,
--  CHANNEL_FIRST,
  COUNT_ISSUE,
  PCT_RESOLVED,
  PCT_RESOLVED_0D,
  PCT_RESOLVED_1D,
  PCT_RESOLVED_3D,
  PCT_RESOLVED_5D,
  PCT_RESOLVED_7D,
  PCT_RESOLVED_10D
FROM temp 
ORDER BY 1 DESC;

-- OUTPUT 1 (GSHEET DOC)
--------------------



--------------------
-- 2) BEST/WORST CHANNEL PER COUNTRY
--------------------

-- % percent of issues resolved per CHANNEL_LAST (I consider the last channel as channel that resolved)

with temp as (
SELECT 
  COUNTRY,
  COALESCE(CHANNEL_LAST,CHANNEL_FIRST) AS CHANNEL,
  COUNT(DISTINCT ISSUE_KEY) AS COUNT_ISSUE,
  ROUND(SAFE_DIVIDE(SUM(COUNT_TOUCHPOINTS),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_TOUCHPOINTS,
  ROUND(SAFE_DIVIDE(SUM(RESPONSE_TIME_HR),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_RESPONSE_TIME_HR,
  ROUND(SAFE_DIVIDE(SUM(ISSUE_RESOLVED_7D),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_7D
FROM `cases-478017.sumup.tbl_issue_merchant` 
GROUP BY 
  1,
  2 )

SELECT 
  COUNTRY,
  CHANNEL,
  COUNT_ISSUE,
  ISSUE_TOUCHPOINTS,
  ISSUE_RESPONSE_TIME_HR,
  PCT_RESOLVED_7D
FROM temp 
WHERE CHANNEL IS NOT NULL
ORDER BY 1,6 DESC
;
-- OUTPUT 2 (GSHEET DOC)
--------------------



--------------------
-- 3) Agent Company performed the best
--------------------

-- % percent of issues resolved per AGENT_COMPANY_LAST (I consider the last agent company as the one that resolved)

with temp as (
SELECT 
 -- COUNTRY,
  COALESCE(CHANNEL_LAST,CHANNEL_FIRST) AS CHANNEL,
  COALESCE(AGENT_COMPANY_LAST,AGENT_COMPANY_FIRST) AS AGENT_COMPANY,
  COUNT(DISTINCT ISSUE_KEY) AS COUNT_ISSUE,
  ROUND(SAFE_DIVIDE(SUM(COUNT_AGENTS),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_AGENTS,
 -- ROUND(SAFE_DIVIDE(SUM(COUNT_TOUCHPOINTS),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_TOUCHPOINTS,
  ROUND(SAFE_DIVIDE(SUM(RESPONSE_TIME_HR),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_RESPONSE_TIME_HR,
 -- ROUND(SAFE_DIVIDE(SUM(TOTAL_HANDLING_TIME_HR),COUNT(DISTINCT ISSUE_KEY)),2) AS ISSUE_HANDLING_TIME_HR,
  ROUND(SAFE_DIVIDE(SUM(ISSUE_RESOLVED_7D),COUNT(DISTINCT ISSUE_KEY)) * 100,2) AS PCT_RESOLVED_7D
FROM `cases-478017.sumup.tbl_issue_merchant` 
GROUP BY 
  1,2 
)

SELECT 
  CHANNEL,
  AGENT_COMPANY,
  COUNT_ISSUE,
  ISSUE_AGENTS,
  ISSUE_RESPONSE_TIME_HR,
  PCT_RESOLVED_7D
FROM temp 
WHERE AGENT_COMPANY NOT IN ('System', '')
ORDER BY 
  1,2
;
-- OUTPUT 3 and 4 (no channel) (GSHEET DOC)
--------------------





--------------------
-- 4) Costs to each channel
--------------------

SELECT 
CHANNEL,
COUNT(DISTINCT AGENT_ID) AS DIST_AGENT,
COUNT(TOUCHPOINT_ID) as COUNT_TOUCHPOINT,
SUM(TOTAL_HANDLING_TIME_SECONDS) as SUM_HANDLING_TIME
FROM `cases-478017.sumup.rawdata`
GROUP BY 1;
-- Only 1 agent, and no handling time for email. So, the approach for email will be different than other channels

-- OUTPUT 5 (GSHEET DOC)
--------------------


-- EMAIL
SELECT
EXTRACT(MONTH FROM TIMESTAMP(CREATED_AT)) AS MONTH,
COUNT(DISTINCT AGENT_ID) AS DIST_AGENT
FROM `cases-478017.sumup.rawdata`
GROUP BY 1
ORDER BY 1;
-- OUTPUT 6 (GSHEET DOC)
--------------------


-- CHAT AND CALL
WITH base AS (
  SELECT 
  EXTRACT(MONTH FROM TIMESTAMP(CREATED_AT)) AS MONTH,
  CHANNEL,
  SUM(CASE WHEN CHANNEL = 'chat' THEN ROUND(SAFE_DIVIDE(TOTAL_HANDLING_TIME_SECONDS,3),0) ELSE TOTAL_HANDLING_TIME_SECONDS END) AS SUM_ADJUSTED_HANDLING_TIME -- 3 chats at the same time
  FROM `cases-478017.sumup.rawdata`
  WHERE CHANNEL IN ('chat','call')
  GROUP BY 1,2
  ORDER BY 1,2
),
pct AS (
SELECT
  MONTH,
  CHANNEL,
  SUM_ADJUSTED_HANDLING_TIME,
  ROUND(SAFE_DIVIDE(SUM_ADJUSTED_HANDLING_TIME,SUM(SUM_ADJUSTED_HANDLING_TIME) OVER (PARTITION BY MONTH)),2) AS PCT_HANDLING_TIME,
FROM base
)

SELECT
  MONTH,
  CHANNEL,
  SUM_ADJUSTED_HANDLING_TIME,
  PCT_HANDLING_TIME,
  ROUND(AVG(PCT_HANDLING_TIME) OVER (PARTITION BY CHANNEL),2) AS AVG_PCT_HANDLING_TIME_BY_CHANNEL
FROM pct
ORDER BY
  1,2

-- OUTPUT 7 (GSHEET DOC)
--------------------
